---
name: "Checks"

on: [push]

jobs:
    test-lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Login To Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Check
              uses: actions/checkout@v4 
            - name: Test
              run: docker compose run --rm app sh -c "python manage.py test"
            - name: Lint
              run: docker compose run --rm app sh -c "flake8"